-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    password_hash character varying(200) NOT NULL,
    role character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.card_table
(
    id integer NOT NULL,
    module integer NOT NULL,
    creator character varying(20) NOT NULL,
    tag character varying(20) NOT NULL,
    question character varying(200) NOT NULL,
    answer character varying(200) NOT NULL,
    deck character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deck_table
(
    deck character varying(20) NOT NULL,
    deck_id integer NOT NULL,
    username character varying(20) NOT NULL,
    PRIMARY KEY (deck_id)
);

CREATE TABLE IF NOT EXISTS public.deck_card_table
(
    card_id integer NOT NULL,
    deck_id integer NOT NULL,
    PRIMARY KEY (card_id, deck_id)
);

ALTER TABLE public.deck_table
    ADD FOREIGN KEY (username)
    REFERENCES public.users (username)
    NOT VALID;


ALTER TABLE public.card_table
    ADD FOREIGN KEY (creator)
    REFERENCES public.users (username)
    NOT VALID;


ALTER TABLE public.deck_card_table
    ADD FOREIGN KEY (card_id)
    REFERENCES public.card_table (id)
    NOT VALID;


ALTER TABLE public.deck_card_table
    ADD FOREIGN KEY (deck_id)
    REFERENCES public.deck_table (deck_id)
    NOT VALID;

END;