-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

-- ********************************************************************************
-- BELOW is the copied script from the Seed Code
-- ********************************************************************************

BEGIN TRANSACTION;

--ROLLBACK;


DROP TABLE IF EXISTS users, card_table, deck_table, deck_card_table CASCADE;
DROP SEQUENCE IF EXISTS seq_user_id, card_table_serial, deck_table_serial;

CREATE SEQUENCE seq_user_id
  INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;


CREATE TABLE users (
	user_id int DEFAULT nextval('seq_user_id'::regclass) NOT NULL,
	username varchar(50) NOT NULL UNIQUE,
	password_hash varchar(200) NOT NULL,
	role varchar(50) NOT NULL,
	CONSTRAINT PK_user PRIMARY KEY (user_id)
);

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

-- 	********************************************************************************
-- 	This script creates the database users and grants them the necessary permissions
-- 	********************************************************************************

-- CREATE USER final_capstone_owner
-- WITH PASSWORD 'finalcapstone';

GRANT ALL
ON ALL TABLES IN SCHEMA public
TO final_capstone_owner;

GRANT ALL
ON ALL SEQUENCES IN SCHEMA public
TO final_capstone_owner;

-- CREATE USER final_capstone_appuser
-- WITH PASSWORD 'finalcapstone';

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO final_capstone_appuser;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO final_capstone_appuser;


-- ********************************************************************************
-- ABOVE is the copied script from the Seed Code
-- ********************************************************************************


--DROP TABLE IF EXISTS card_table, deck_table, deck_card_table; --CASCADE;


CREATE SEQUENCE card_table_serial;
CREATE TABLE IF NOT EXISTS public.card_table
(
    id integer NOT NULL DEFAULT nextval('card_table_serial'),
    module integer NOT NULL,
    creator character varying(50) NOT NULL,
    tag character varying(50) NOT NULL,
    question character varying(300) NOT NULL,
    answer character varying(300) NOT NULL,
    deck character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE SEQUENCE deck_table_serial;
CREATE TABLE IF NOT EXISTS public.deck_table
(
    deck character varying(50) NOT NULL,
    deck_id integer NOT NULL DEFAULT nextval('deck_table_serial'),
    username character varying(50) NOT NULL,
    PRIMARY KEY (deck_id)
);

CREATE TABLE IF NOT EXISTS public.deck_card_table
(
    card_id integer NOT NULL,
    deck_id integer NOT NULL,
    PRIMARY KEY (card_id, deck_id)
);

ALTER TABLE public.deck_table
    ADD FOREIGN KEY (username)
    REFERENCES public.users (username)
    NOT VALID;


ALTER TABLE public.card_table
    ADD FOREIGN KEY (creator)
    REFERENCES public.users (username)
    NOT VALID;


ALTER TABLE public.deck_card_table
    ADD FOREIGN KEY (card_id)
    REFERENCES public.card_table (id)
    NOT VALID;


ALTER TABLE public.deck_card_table
    ADD FOREIGN KEY (deck_id)
    REFERENCES public.deck_table (deck_id)
    NOT VALID;
	
INSERT INTO card_table (id, module, creator, tag, question, answer, deck) VALUES (1, '3', 'admin', 'DOM', 'What does DOM stand for?', 'Document Object Model', 'Tech Elevator - Default');



COMMIT TRANSACTION;